# 프로덕션: https://uandimilestudio-828.netlify.app/
# Netlify 프로젝트 uandimilestudio-828

[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
